// react+ts+rtk/src/components/TodoInput/index.tsx
import { memo, useState } from "react";
import type { FC, ReactNode } from "react";
import { useTodo } from "../../hooks";
interface IProps {
  children?: ReactNode;
}
const TodoInput: FC<IProps> = () => {
  const [todoVal, setTodoVal] = useState<string>("www");
  const { setTodo } = useTodo();
  const setTodoValue = (e: any) => {
    setTodoVal(e.target.value);
    if (e.key === "Enter" && todoVal.trim().length) {
      setTodo(todoVal);
    }
  };
  return (
    <input
      type='text'
      onChange={setTodoValue}
      onKeyUp={setTodoValue}
      value={todoVal}
    />
  );
};
export default memo(TodoInput);

// v3+ts+vuex/src/components/TodoInput.vue
<template>
  <div class="todoInput">
    <input type="text" v-model="todoVal" @keyup="setTodoVal" />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { useTodo } from "../hooks";
export default defineComponent({
  setup() {
    const todoVal = ref<string>("");
    const { setTodo } = useTodo();
    function setTodoVal(e: KeyboardEvent): void {
      if (e.key === "Enter" && todoVal.value.trim().length) {
        setTodo(todoVal.value);
        todoVal.value = "";
      }
    }
    return {
      todoVal,
      setTodoVal,
    };
  },
});
</script>

<style scoped></style>
