// react+ts+rtk/src/components/TodoLit/item.tsx
import { memo } from "react";
import type { FC, ReactNode } from "react";
import cs from "classnames";
import { ITodo, TODO_STATUS } from "../../types";
import itemStyle from "./index.module.scss";
interface IProps {
  children?: ReactNode;
  item: ITodo;
  setStatus: (id: number) => any;
}
const TodoItem: FC<IProps> = ({ item, setStatus }) => {
  const { FINISHED } = {
    FINISHED: TODO_STATUS.FINISHED,
    // DOING: TODO_STATUS.DOING,
    // WILLDO: TODO_STATUS.WILLDO,
  };
  return (
    <div>
      <input
        type='checkbox'
        defaultChecked={item.status === FINISHED}
        onClick={() => setStatus(item.id)}
      />
      <span className={cs(item.status === FINISHED && itemStyle.lineThrough)}>
        {item.content}
      </span>
      <button>删除</button>
      <button></button>
    </div>
  );
};
export default memo(TodoItem);

// v3+ts+pinia+vite/src/components/TodoList/item.vue
<template>
  <div class="todoItem">
    <input type="checkbox" @click="setStatus(item.id)" />
    <span :class="item.status === statusState.FINISHED ? 'line-through' : ''">{{
      item.content
    }}</span>
    <button @click="removeTodo(item.id)">删除</button>
    <button @click="setDoing(item.id)">
      {{ item.status === statusState.DOING ? "正在做" : "马上做" }}
    </button>
  </div>
</template>

<script lang="ts" setup>
import { PropType } from "vue";
import { ITodo, TODO_STATIS } from "../../types";

defineProps({
  item: {
    type: Object as PropType<ITodo>,
    required: true,
  },
});
const emit = defineEmits(["removeTodo", "setStatus", "setDoing"]);
const statusState = {
  FINISHED: TODO_STATIS.FINISHED,
  WILLDO: TODO_STATIS.WILLDO,
  DOING: TODO_STATIS.DOING,
};

const removeTodo = (id: number) => emit("removeTodo", id);
const setStatus = (id: number) => emit("setStatus", id);
const setDoing = (id: number) => emit("setDoing", id);
</script>

<style scoped>
.line-through {
  text-decoration: line-through;
}
</style>
