// v3+ts+pinia+vite/src/App.vue
<template>
  <div class="app">
    <todo-input />
    <todo-list :todoList="todoList" />
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted } from "vue";
import { useTodo } from "./hooks";
import useList from "./store/listStore";
import TodoInput from "./components/TodoInput/index.vue";
import TodoList from "./components/TodoList/index.vue";

const { setTodoList } = useTodo();
const listStore = useList();
const todoList = computed(() => listStore.list);
onMounted(() => setTodoList());
</script>

<style scoped></style>

// react+ts+rtk/src/App.tsx
import { memo, ReactNode, useEffect } from "react";
import type { FC } from "react";
import { connect } from "react-redux";
import { IRootState } from "./store";
import { ITodo } from "./types";
import { useTodo } from "./hooks";
import TodoInput from "./components/TodoInput";
import TodoLit from "./components/TodoLit";
interface IProps {
  children?: ReactNode;
  list: ITodo[];
}
const App: FC<IProps> = ({ list }) => {
  const { setTodoList } = useTodo();
  useEffect(() => {
    setTodoList();
  }, []);
  return (
    <div className='App'>
      <TodoInput />
      <TodoLit list={list} />
    </div>
  );
};
export default connect((state: IRootState) => ({
  list: state.list.list,
}))(memo(App));
