// react+ts+rtk/src/App.tsx
import { memo, ReactNode, useEffect } from "react";
import type { FC } from "react";
import { connect } from "react-redux";
import { IRootState } from "./store";
import { ITodo } from "./types";
import { useTodo } from "./hooks";
import TodoInput from "./components/TodoInput";
import TodoLit from "./components/TodoLit";
interface IProps {
  children?: ReactNode;
  list: ITodo[];
}
const App: FC<IProps> = ({ list }) => {
  const { setTodoList } = useTodo();
  useEffect(() => {
    setTodoList();
  }, []);
  return (
    <div className='App'>
      <TodoInput />
      <TodoLit list={list} />
    </div>
  );
};
export default connect((state: IRootState) => ({
  list: state.list.list,
}))(memo(App));

// v3+ts+vuex/src/App.vue
<template>
  <div class="warpper">
    <todo-input />
    <todo-list :todoList="todoList" />
  </div>
</template>

<script lang="ts">
import { computed, ComputedRef, defineComponent, onMounted } from "vue";
import { useTodo } from "@/hooks";
import { useStore } from "vuex";
import { ITodo } from "./types";
import TodoInput from "./components/TodoInput.vue";
import TodoList from "./components/TodoList.vue";

export default defineComponent({
  name: "App",
  components: {
    TodoInput,
    TodoList,
  },
  setup() {
    const store = useStore();
    const todoList: ComputedRef<ITodo[]> = computed(() => store.state.list);
    const { setTodoList } = useTodo();
    onMounted(() => {
      setTodoList();
    });
    return {
      todoList,
    };
  },
});
</script>
